// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerLibrary.Data;

#nullable disable

namespace ServerLibrary.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260409190102_Create_db_Schema")]
    partial class Create_db_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseLibrary.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobilenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("physicalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BaseLibrary.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("Applicationusers");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Chiefdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chiefdoms");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ChiefdomId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ChiefdomId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("VillageId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BaseLibrary.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Person", b =>
                {
                    b.Property<string>("nationalid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int");

                    b.Property<int?>("addressId")
                        .HasColumnType("int");

                    b.Property<int>("addresseid")
                        .HasColumnType("int");

                    b.Property<int>("chiefdomid")
                        .HasColumnType("int");

                    b.Property<int>("districtid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("provinceid")
                        .HasColumnType("int");

                    b.Property<string>("village")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nationalid");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VillageId");

                    b.HasIndex("addressId");

                    b.HasIndex("chiefdomid");

                    b.HasIndex("districtid");

                    b.HasIndex("provinceid");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("BaseLibrary.Entities.SystemRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("BaseLibrary.Entities.UserRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("roleid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Company", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Address", null)
                        .WithMany("company")
                        .HasForeignKey("AddressId");

                    b.HasOne("BaseLibrary.Entities.Chiefdom", null)
                        .WithMany("company")
                        .HasForeignKey("ChiefdomId");

                    b.HasOne("BaseLibrary.Entities.Company", null)
                        .WithMany("company")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BaseLibrary.Entities.District", null)
                        .WithMany("company")
                        .HasForeignKey("DistrictId");

                    b.HasOne("BaseLibrary.Entities.Province", null)
                        .WithMany("company")
                        .HasForeignKey("ProvinceId");

                    b.HasOne("BaseLibrary.Entities.Village", null)
                        .WithMany("company")
                        .HasForeignKey("VillageId");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Person", b =>
                {
                    b.HasOne("BaseLibrary.Entities.Company", null)
                        .WithMany("person")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BaseLibrary.Entities.Village", null)
                        .WithMany("person")
                        .HasForeignKey("VillageId");

                    b.HasOne("BaseLibrary.Entities.Address", "address")
                        .WithMany("person")
                        .HasForeignKey("addressId");

                    b.HasOne("BaseLibrary.Entities.Chiefdom", "chief")
                        .WithMany("person")
                        .HasForeignKey("chiefdomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.District", "district")
                        .WithMany("person")
                        .HasForeignKey("districtid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Entities.Province", "province")
                        .WithMany("person")
                        .HasForeignKey("provinceid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("address");

                    b.Navigation("chief");

                    b.Navigation("district");

                    b.Navigation("province");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Address", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Chiefdom", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Company", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });

            modelBuilder.Entity("BaseLibrary.Entities.District", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Province", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });

            modelBuilder.Entity("BaseLibrary.Entities.Village", b =>
                {
                    b.Navigation("company");

                    b.Navigation("person");
                });
#pragma warning restore 612, 618
        }
    }
}
