using Microsoft.EntityFrameworkCore;
using ServerLibrary.Data;
using ServerLibrary.Helpers;
using ServerLibrary.Repository.Contract;
using ServerLibrary.Repository.Implementation;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.


builder.Services.AddDbContext<AppDBContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Invalid Operation"),
     b => b.MigrationsAssembly("ServerLibrary") ));

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Add Swagger generator if using custom Swashbuckle filters or legacy features
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
//builder.Services.AddDbContext<AppDBContext>(options =>
//{
//    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Invalid Operation"));
//});



//builder.Services.AddDbContext<AppDBContext>(options =>
//    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.Configure<JwtSection>(builder.Configuration.GetSection("JwtSection"));
builder.Services.AddScoped<IUserAccount, UserAccountRepository>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Generates the openapi/v1.json endpoint
    // app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI();
    // Enables Swagger UI and points it to the OpenAPI document
    //app.UseSwaggerUI(options =>
    //{
    //    // Path to the OpenAPI JSON file generated by .NET 10
    //    //  options.SwaggerEndpoint("/openapi/v1.json", "TestAPI");
    //    options.SwaggerEndpoint("/swagger/v1/swagger.json", "TestAPI");
    //});
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
