using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using ServerLibrary.Data;
using ServerLibrary.Helpers;
using ServerLibrary.Repository.Contract;
using ServerLibrary.Repository.Implementation;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.


builder.Services.AddDbContext<AppDBContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Invalid Operation"),
     b => b.MigrationsAssembly("ServerLibrary") ));

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Add Swagger generator if using custom Swashbuckle filters or legacy features
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.Configure<JwtSection>(builder.Configuration.GetSection("JwtSection"));
var jwtSection = builder.Configuration.GetSection(nameof(JwtSection)).Get<JwtSection>();
//builder.Services.AddDbContext<AppDBContext>(options =>
//{
//    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Invalid Operation"));
//});



//builder.Services.AddDbContext<AppDBContext>(options =>
//    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true, // validate the server that issued the token
        ValidateAudience = true, // validate the recipient of the token
        ValidateLifetime = true, // validate token expiration
        ValidateIssuerSigningKey = true, // validate signature

        ValidIssuer = jwtSection!.Issuer,//builder.Configuration["Jwt:Issuer"],       // e.g. "https://yourdomain.com"
        ValidAudience = jwtSection.Audience,// builder.Configuration["Jwt:Audience"],   // e.g. "https://yourdomain.com"
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSection.Key)) // secret key
    };
});


builder.Services.AddScoped<IUserAccount, UserAccountRepository>();
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowBlazorWasm",
    builder => builder
    .WithOrigins("https://localhost:7084","http://localhost:5226")
    .AllowAnyMethod()
    .AllowAnyHeader()
    .AllowCredentials());
}
);
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Generates the openapi/v1.json endpoint
    // app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI();
    // Enables Swagger UI and points it to the OpenAPI document
    //app.UseSwaggerUI(options =>
    //{
    //    // Path to the OpenAPI JSON file generated by .NET 10
    //    //  options.SwaggerEndpoint("/openapi/v1.json", "TestAPI");
    //    options.SwaggerEndpoint("/swagger/v1/swagger.json", "TestAPI");
    //});
}

app.UseHttpsRedirection();

app.UseCors("AllowBlazorWasm");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
